apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot-service
  name: bot-service
spec:
  ports:
    - name: 'bot-svc'
      nodePort: 30080
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: bot-service
  type: NodePort
